apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap   # name of the configmap, will use this in front end pod mongoexpress to connect to mongodb service to route traffic to mongodb. 
  namespace: mongo-project
data:
  database_url: mongodb-service  # name of service listening to mongo db pod
  mongo-root-username: admin
  mongo-root-password: password
