apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    namespace: mongo-project
type: Opaque
data:
  # mongo-root-username: dXNlcm5hbWU=   use "echo dXNlcm5hbWU= | base64 --decode" to decode, use  "echo -n 'username' | base64" to encode
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=

